name: Build LaTeX and Update PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build LaTeX
        run: docker-compose up -d latex-build

      - name: Wait for LaTeX Build to Finish
        run: |
          while [ "$(docker ps -q -f name=latex-build)" ]; do
            sleep 1
          done

      - name: Check for Changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git config user.name "Jordan"
            git config user.email "jordanwmckee@outlook.com"
            git add resume.pdf
            git commit -m "Update PDF"
            git push
          fi
